<?php // in module/Application/view/partial/breadcrumb.phtml: ?>
<ul class="breadcrumb">
    <?php foreach ($this->pages as $key => $page) : ?>
        <li>
            <?php if ($key < count($this->pages) - 1) :
                ?><a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a>
            <?php else :
                ?> <?= $page->getLabel() ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>