<div class="container text-center">
    <h3>Login</h3>
</div>

<div class="container">
    <form class="form-signin" id="loginForm">
        <div class="form-label-group">
            <label for="inputEmail">Email address</label>
            <input type="email" name="email" class="form-control" placeholder="Email address" autofocus="">
        </div>

        <div class="form-label-group">
            <label for="inputPassword">Password</label>
            <input type="password" name="password" class="form-control" placeholder="Password" required="">
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>