<div class="container">
    <h3>About this module</h3>
    <p>
        This module developed using Zend framework standard guide line followed by
        <a href="https://docs.zendframework.com/tutorials/getting-started/overview/">Getting Started with Zend Framework MVC Applications</a>
    </p>
    <p>What inside this module</p>
    <ul class="module-future">
        <li>Sqlite database</li>
        <li>Dedicated sqlite database for this module</li>
        <li>Passing javascript from controller to view</li>
    </ul>
</div>